# Fake secrets for testing purposes only.
AWS_ACCESS_KEY_ID = "AKIAIOSFODNN7EXAMPLE"
AWS_SECRET_ACCESS_KEY = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
AWS_ACCESS_KEY_ID = "AKIA1234567890ABCDE"
AWS_SECRET_ACCESS_KEY = "abcdEFGHijklMNOPqrstUVWXyz1234567890abcd"
